### ISSUE TITLE
Venu 3 compatibility 

### ISSUE THREAD

**Issue by IlyaChaban** [aguilarguisado/JSONFace#1]
Will there be added Venu 3 compatibility?

**Comment by aguilarguisado** [comment]
Hi @IlyaChaban. I have added support to Venu3. I'm uploading the new version to Connect IQ Store. It should be available in less than one hour. Thank you for asking!

**Comment by IlyaChaban** [comment]
@aguilarguisado maaaaan! You are the speed)
Thank you so much.🔥🔥🔥
